sudo: required
services:
  - docker

before_install:
  - docker build -t jyotirmoy/dockerreactapp -f Dockerfile.dev .


script:
  - docker run jyotirmoy/dockerreactapp npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockereactapp"
  env: "Dockereactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-372429655974"
  bucket_path: "dockereactapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
